version: "3"

services:
  keosd:
    image: eosio/eos-dev:v1.5.2
    hostname: keosd
    command: /bin/bash -c "keosd --http-server-address keosd:8899"
    volumes:
      - ./eosio/data:/data
    networks:
      eosio:
        aliases:
          - keosd
  nodeosd:
    container_name: "eosio-block-questions"
    build: ./eosio
    hostname: nodeosd
    volumes:
      - ./eosio/data:/data
    networks:
      eosio:
        aliases:
          - nodeosd

  mongo:
    ports:
      - 27017:27017
    hostname: mongo
    image: mongo:4
    networks:
      eosio:
        aliases:
          - mongo

networks:
  eosio:
